version: '2'


services:

  storage:
    env_file:
      - ./secrets.env

    image: tarantool/tarantool:1.7
    environment:
      STORAGE_PORT: "33011"

    ports:
      - "127.0.0.1:33011:33011"
    volumes:
      - /var/lib/tarantool/microb_storage/:/var/lib/tarantool/
      - ./start_storage.lua:/opt/tarantool/start_storage.lua
      - ./microb:/usr/local/share/tarantool/microb
    restart: always
    command: ['tarantool', '/opt/tarantool/start_storage.lua']


  web:
    env_file:
      - ./secrets.env

    image: tarantool/tarantool:1.7
    environment:
      STORAGE_HOST: "storage"
      STORAGE_PORT: "33011"

    links:
      - storage
    ports:
      - "127.0.0.1:8080:22222"
    volumes:
      - /var/lib/tarantool/microb_web/:/var/lib/tarantool/
      - ./start_web.lua:/opt/tarantool/start_web.lua
      - ./microb:/usr/local/share/tarantool/microb
    restart: always
    command: ['tarantool', '/opt/tarantool/start_web.lua']
